services:
  reports:
    env_file:
      - .env
    container_name: reports
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '127.0.0.1:${PORT}:${PORT}'
    restart: always
    networks:
      - default

networks:
  default:
    external: false
